FuryRent/Controllers/PayController.cs
using FuryRent.Core.Contracts;
using FuryRent.Core.Models.Pay;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FuryRent.Controllers
{
	[Authorize]
	public class PayController : Controller
	{
		private readonly IPayService payments;

		public PayController(IPayService _payments)
		{
			payments = _payments;
		}

		[HttpGet]
		[Authorize(Roles = "Admin, User")]
		public async Task<IActionResult> PayRent(int id)
		{
			var rent = await payments.GetRentById(id);

			if(rent == null)
			{
				return NotFound();
			}

			var model = new PayServiceViewModel()
			{
				PaymentAmount = rent.PaymentAmount,
				RentId = rent.RentId,
				PaymentTypes = await payments.GetPaymentTypes()
			};

			return View(model);
		}

		[HttpPost]
		[Authorize(Roles = "Admin, User")]
		public async Task<IActionResult> PayRent(PayServiceViewModel model, int id)
		{
			var rent = await payments.GetRentById(id);

			model.PaymentAmount = rent.PaymentAmount;
			model.RentId = rent.RentId;

			if (!ModelState.IsValid)
            {
                model.PaymentTypes = await payments.GetPaymentTypes();

                return RedirectToAction(nameof(PayRent));
            }

			try
			{
                await payments.Pay(model);
            }
			catch (Exception)
			{

				return BadRequest();
			}

            TempData["message"] = "The payment was successfull!";

            return RedirectToAction("All", "Rent");
		}
	}
}

FuryRent/Controllers/RentController.cs
using FuryRent.Core.Contracts;
using FuryRent.Core.Exceptions;
using FuryRent.Core.Models.Rent;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FuryRent.Controllers
{
	[Authorize]
	public class RentController : Controller
	{
		private readonly IRentService rents;

		public RentController(IRentService _rents)
		{
			rents = _rents;
		}

		[Authorize(Roles = "Admin, User")]
		public async Task<IActionResult> All()
		{
			var userId = GetUserId();

			var model = await rents.All(userId);

			return View(model);
		}

		[HttpGet]
		[Authorize(Roles = "Admin, User")]
		public IActionResult Add()
		{
		
			return View();
		}

		[HttpPost]
		[Authorize(Roles = "Admin, User")]
		public async Task<IActionResult> Add(AddRentViewModel rentModel, int Id)
		{
			var userId = GetUserId();

			try
			{
                await rents.Add(rentModel, userId, Id);
            }
			catch (NoSuchCarException)
			{

				return NotFound();
			}
			catch(InvalidOperationException exc)
			{
                TempData["message"] = exc.Message;

                return RedirectToAction("Details", "Car", new {Id});
            }
			catch(Exception exc)
			{
				TempData["message"] = exc.Message;

				return RedirectToAction("Become", "Vip");
			}

            TempData["message"] = "You have successfully rented a car";

            return RedirectToAction("All", "Rent");
		}

		private string GetUserId()
		{
			return User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
		}
	}
}

FuryRent/Views/Rent/Add.cshtml
@model AddRentViewModel

@{
	ViewBag.Title = "Rent";
}


<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
	<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
		<form asp-action="Add" method="post">
			<div class="mb-3">
				<label asp-for="@Model.RentalStartDate" class="form-label-add-edit">Pick up date</label>
				<input asp-for="@Model.RentalStartDate" class="form-control" aria-required="true" />
				<span asp-validation-for="@Model.RentalStartDate" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.RentalEndDate" class="form-label-add-edit">Return date</label>
				<input asp-for="@Model.RentalEndDate" class="form-control" aria-required="true" />
				<span asp-validation-for="@Model.RentalEndDate" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<input class="btn btn-outline-success mb-2 w-100 p-3 fw-bold" type="submit" value="Rent" />
			</div>
		</form>
	</div>
</div>


@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

FuryRent/Views/Rent/All.cshtml
@model IEnumerable<RentViewModel>

<head>
	@{
		ViewData["Title"] = "My Rents";
	}
	<link href="~/css/site.css" />
</head>

<h2 class="text-center">@ViewData["Title"]</h2>

<hr />

@if (!Model.Any())
{
	<div class="alert alert-danger mt-2 text-center fw-bold" role="alert">
		No rents yet!
	</div>
}

<div class="card-deck">
	@foreach (var rent in Model)
	{
		<div class="card border-1 border-danger mb-3" style="width: 45rem;">
			<img src="@rent.ImageUrl" class="card-img-top" alt="@rent.Make @rent.Model">
			<div class="card-body">
				<h5 class="card-title">@rent.Make @rent.Model</h5>
				<p class="card-model"><span class="fw-bold">Price per day: </span>@rent.PricePerDay$</p>
				<p class="card-model"><span class="fw-bold">Pick up Date: </span>@rent.RentalStartDate.ToString(CarConstants.DateFormat, CultureInfo.InvariantCulture)</p>
				<p class="card-model"><span class="fw-bold">Return Date: </span>@rent.RentalEndDate.ToString(CarConstants.DateFormat, CultureInfo.InvariantCulture)</p>
				<p class="card-model"><span class="fw-bold">Total: </span>@rent.TotalCost$</p>
				@{
					if(rent.IsPaid)
					{
						<a class="btn btn-danger disabled">Paid</a>
					}
					else
					{
						<a asp-controller="Pay" asp-action="PayRent" asp-route-id="@rent.Id" class="btn btn-danger">Pay</a>
					}
				}
			</div>
		</div>
	}
</div>